apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCFmLwtWMhzmeVh3DUPSutITouYkMGrSMHVSqGqrsKaYoPJBUE4KieN51SQhjZUYcdldYK4AUR09BL9JL399o3Qv+VxSBo8mCgc73WxecjFcSgZaLU2cpF4zwpIGnw9D8Y8jpLSSzllN5/7eptpGowii2Q/cJVtOuQEbe41Kd/ZmQu2b+TsL22iAXQEYDNR0zzzypYISjM6wPvxf8klRc4r88fnzeWZGHVB5ec0UBpKvOwxqH2HqmmVfmK9lDEsQHQsDNZN9GE4DJY2xtmnK0vZvo675xZjE1w3cuReSL8Yn2g2WJeSVKsK7AQVhPFyyykUJjsDWtadSZBaWvPioBbBvJC+YGUA2RBIOqpaTQDBiMbeCAeggFzkLi06ZTte5Gmx9/7lECXrMQ+UnVd4w4asHnB6vnp6zEO8YP3fr7YXdsr2Ns8ZRAW6OMzEApCS6v3GaifpTxzk0wgQIFRop0TMoJ2aVH8N0e9Ym/NXaaenlCZcpb/dofV+FVPX7gz1s20qSwRNtnwKH1/Fk8wR5/lgVni/fzf75h2gyM0aucdI293h+UE1JYMSV1D/WmfkyTLTup37+tRi+KJZl5GwZIK7kshOm8+fnzeZKMhzCD09lIj9VOK56GD83hsRVwmh4bqdQH51BTXDgpUoct/08SEdisCuEdBlOYD1894NwLLa+7ht+t4bQp4GV3fIEctrxy1qnqL0QsQxhcE60JmPPugdiF58IFCBTOSN9+OAjSDRtb6kfJEM1gR7s+HD70G15nkUgaFpO9xuNNjquBhprfakbwDn53j5AzVJFnOhHYxQhKhNalSCGOp+j8u23PU=
  template:
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
