#!/bin/bash
set -euo pipefail

# =============================================================
# Sealed Secrets key restoration
#
# Restores the sealing key (disaster recovery) into the cluster.
# Only needed when restoring from a backup — skip on a fresh
# install (a new key will be generated by the controller).
# =============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEY_FILE="$SCRIPT_DIR/sealing-key-backup.yaml"

if [ ! -f "$KEY_FILE" ]; then
    echo "ERROR: sealing key not found at: $KEY_FILE" >&2
    echo "Nothing to do on a fresh install — you can skip this script." >&2
    exit 1
fi

echo "=== Sealed Secrets key restoration ==="

# Create the namespace (idempotent — safe to re-run)
kubectl get namespace sealed-secrets >/dev/null 2>&1 || kubectl create namespace sealed-secrets

# Apply the sealing key as a Kubernetes secret
kubectl apply -f "$KEY_FILE"

echo "Sealed Secrets key restored into namespace 'sealed-secrets'."
