apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blocky
  namespace: networking
  labels:
    app.kubernetes.io/name: blocky
    app.kubernetes.io/instance: blocky
spec:
  namespaceSelector:
    matchNames:
      - networking
  selector:
    matchLabels:
      app.kubernetes.io/name: blocky
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
