apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gickup-secrets
  namespace: gickup
spec:
  encryptedData:
    github-token: AgCf1eH24I5L6IGXrGvFtDnlTdmvWVZ6yMC7T32mNrP2uBxUHGOmfa6yWypxsRUuWTA7KZJCtj5r5ShgrL4zlr2asfu+fcID/9Nbm77BJf7zaOZmI0zGWqJHcvZX//TraqXdQRtrh37y+fL07EJqyEnZn4tBp5TObSmCP3/hlYTAFJBbkKCvNi5CFsDEigEsXi7rUaJUGm0nK2Wwny8FyNoeMwHX1THWPLqyrEWUYeKYs8j8t6mbmrU7EA2z9KW07wg7ZNb42sdjfu2at6KUmLq5tYjwvjqmRQUdv4ZQZYQMLF1h7fvmJhfvbPEDdIhZ6YgyM/SwxxM89XbNfk8S9WjeABvDmomQ+9xsj6IXnX6TziSwHlOgRVUYwFum8rnoaZrN7YN7h8SwFic/KhhrMJ0KtbJHzDTeNRL+X2j4QMlXz3kIS96tjRPnurZqx71zcpMob/OaCtnT6vKoZDsMJO3iUrE/VrCghQewt6vw7cqnppvkVnGNJhSwIXtp8JAN5UmHLV2XD93q+cTsPPlBlu/VM322a/QvOkU0mckRFLddZnDFXdu0CwEsr7PKoAHycI+Hh7yucKKkQPlKNbg8wZEgXuluJj+OJrNMMgv/Qs06CZKHUqFG9MFpUSkE60HbQYqn3XCQnk1e6wuPryPeAuzmXxAWzp0nMc7QqECTMnVgqEsjxtK7DdSn+176dibZp1S/y5kGJ7sobhGecspGALd/BZSiKjZ9oUMYRrVVxKi1c3Tq1TvjlM70
  template:
    metadata:
      creationTimestamp: null
      name: gickup-secrets
      namespace: gickup
