apiVersion: v1
kind: PersistentVolume
metadata:
  name: gickup-backups
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/nas/Backups
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nas-local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gickup-backups
  namespace: gickup
spec:
  volumeName: gickup-backups
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
