apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    client_id: AgCOv2MS7gE1shCOpYyxciKyd7G8FEmTk//3zntrMH2WFvU1k2LWPJL75Ec7XZ06gjDHydyHphsR4fOKuGaxYnZu2R1dnk9e3MXdqxyg8837u6yuvUeoW6klPAk3NCm09bqkLfgP3cp5BBnKqJH39yusiZTtHrCYGs7GymVi9EfvhB7Boa5s63KHSftwE1qditMLoRGdrn42Jnuy+skkVDPn5Uv9T8zbPQvi+3zsrlcCdNZCr/TQkhSHw7Tpup3Ywr5CrkiupgcwxGF8bhAbi21RLMpLnLTGJ02gJMNgj1mv4NrSA7vCiQQlCIDIivUDhUkW5ifmwX4laGY20VckwgGY5tEhvb+0iIxONYAIduG9S2UdVKaHID6SKmAJOqzvGzy4CCtvj+XFrF4V+cpJ7OljWhgY9OohnIqQrbp9llc0WiPmNr1amPqYcTRkrBbUElUXtTQd6isTDHNnKB95r6FBnRFGmZDClmHj5tR3Lz4ufBx5sCRgikPSd215y6kl3BIBLSszObEp8ZpEQFPv7eprxQMgWs+s2zr27hxwTETzw5pZfl5oQRc/8MQ0iM4k+2cXkAVdNknV5bZnFkSK0sZb8bNobSHI2HmKMBUeZ358hD1phmH7EEWUng9PZ8iMO8oQ6lBQnREE3Hii8rJJz/wUrGSu4ARv6Y/tpGhPgtNw9daLCrWLW5OUIgWAYJpbQ4PYl4g1JOiieWypldrqnlnqAw==
    client_secret: AgDO8lHYesN5R2mlHEqF2KIPF6Mbsh1lbqLPMv259SzRy0IsdnMzrwpQHIfxV1ZLotOtWvAWVy6vyboa/jc5S7s07cZDYWw8Xba9kfJM5L69h2zTvINtpxc4Uh4KNxik3l68AQPzM1UNjmWCuC/rVcTY+p+586v7QIGVxi3yVmRWGhGWGZWDRP9m20o0c/Te2ndxJdnUBdLHDclz50iuEo5UuAEtATy5GIUZ1RVhjBQ7inqJGwI6Xf4ZiY7GgUFYQxb4/otc4+62PZcfjrAv4kfn0CbsjOL6hpzNkjEitgpdrieAQqCEuh978xE9z1+j3T4fP+VXi6RvkdQOfm+mBJI8HTIfGJcS+6hKtcxZoMRViAua21iC/GrpKqPs9DM7fHTiBPHCFW0sh6/DaWL9H8QW3tsXeFnM/EMJPnLzojFdOkhUJLevZ5/r8qisNkQaM30KzPai5l5YHcIVgak60iSo1jDqBHud9XWKurpouN1uhn4yI9F2AmBBMt0GaupWMNqP/xljocgnBexd+wHh0AhRByWNvrV/emgQzka870JW+EEx9czSFCz22W54l4VvX6yM6W3oswt6iHkXaKRmm5IEvAMLrQcgW6FTF+4IB7Z475TdCnawDZOFA8G5eRGr8/6u9Nuk9MKAdFwxt2qhJnOLMQvx/l1VquwHivwFZafpCrmECt2RY3hJXo/qHGcGaurcc5/jQcprxyie5CcynfHjHZoZ94lPSjar0VjKus6tzs5TC8Vw46GmsaxKlPcR1E1IdpPumY3c3gExme4nrRc=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
