apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  # This annotation prevents the root-app from deleting ArgoCD
  # even if prune is enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.5.13
    helm:
      values: |
        configs:
          params:
            server.insecure: true
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            hostname: argocd.nas-local.io
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        controller:
          replicas: 1
        dex:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
