apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 85.4.0
    helm:
      values: |
        nodeExporter:
          extraArgs:
            - "--collector.nfs"
            - "--collector.raid"
            - "--collector.diskstats"
          extraVolumes:
            - name: proc
              hostPath:
                path: /proc
            - name: sys
              hostPath:
                path: /sys
            - name: dev
              hostPath:
                path: /dev
          extraVolumeMounts:
            - name: proc
              mountPath: /proc
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: dev
              mountPath: /dev
              readOnly: true
        grafana:
          replicas: 1
          adminPassword: "admin"
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.nas-local.io
            path: /
          service:
            type: ClusterIP
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              searchNamespace: monitoring
            datasources:
              enabled: true
              label: grafana_datasource
              searchNamespace: monitoring
        prometheus:
          prometheusSpec:
            retention: 2d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: microk8s-hostpath
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 1Gi
        prometheusOperator:
          enabled: true
          admissionWebhooks:
            enabled: false
            patch:
              enabled: false
          tls:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
