apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.openwebui.com
      chart: open-webui
      targetRevision: 15.2.0
      helm:
        values: |
          replicaCount: 1
          ollama:
            enabled: false
          pipelines:
            enabled: false
          tika:
            enabled: false
          websocket:
            enabled: false
            redis:
              enabled: false
          persistence:
            enabled: true
            size: 2Gi
            storageClass: microk8s-hostpath
            accessModes:
              - ReadWriteOnce
          extraEnvVars:
            - name: WEBUI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: open-webui-secret
                  key: WEBUI_SECRET_KEY
          ingress:
            enabled: true
            class: nginx
            host: open-webui.nas-local.io
            annotations:
              nginx.ingress.kubernetes.io/proxy-body-size: "50m"
              nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
              nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    - repoURL: https://github.com/marcizhu/microk8s-nas.git
      targetRevision: master
      path: apps/open-webui
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
