apiVersion: v1
kind: Namespace
metadata:
  name: renovate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |-
    {
      "repositories": ["marcizhu/microk8s-nas"],
      "dryRun" : "false",
      "kubernetes": {
        "fileMatch": ["apps/.+\\.yaml$"]
      }
    }

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
  namespace: renovate
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: renovate/renovate:35.14.4
              name: renovate-bot
              env:
                - name: RENOVATE_PLATFORM
                  value: 'github'
                - name: RENOVATE_GIT_AUTHOR
                  value: 'Renovate Bot <bot@renovateapp.com>'
                - name: RENOVATE_AUTODISCOVER
                  value: 'false'
                - name: RENOVATE_BASE_DIR
                  value: '/tmp/renovate/'
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json'
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-secrets
                      key: RENOVATE_TOKEN
              envFrom:
                - secretRef:
                    name: renovate-secrets
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
