apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://media-servarr.shw.al/charts
      chart: transmission
      targetRevision: 0.15.x
      helm:
        values: |
          application:
            config: null
            port: 9091
            urlBase: ''
          deployment:
            initContainers:
              - name: init-config
                image: busybox
                command: ['sh', '-c', 'if [ ! -s /config/settings.json ]; then cp /tmp/settings.json /config/settings.json; fi']
                volumeMounts:
                  - name: config
                    mountPath: '/config'
                  - name: settings-template-vol
                    mountPath: '/tmp/settings.json'
                    subPath: 'settings.json'
            container:
              image:
                repository: 'lscr.io/linuxserver/transmission'
              env:
                - name: 'PUID'
                  value: '1000'
                - name: 'PGID'
                  value: '1000'
                - name: 'TZ'
                  value: 'Europe/Madrid'
              volumeMounts:
                - name: 'config'
                  mountPath: '/config'
                - name: 'data'
                  mountPath: '/data'
            volumes:
              config:
                persistentVolumeClaim:
                  claimName: 'transmission-config'
              settings-template-vol:
                configMap:
                  name: transmission-settings-template
              data:
                hostPath:
                  path: /mnt/nas/Media
                  type: Directory
          persistentVolumeClaims:
            transmission-config:
              accessMode: 'ReadWriteOnce'
              requestStorage: '1Gi'
              storageClassName: 'microk8s-hostpath'
              selector: {}
          service:
            type: ClusterIP
          ingress:
            enabled: true
            host: transmission.nas-local.io
            className: nginx
    - repoURL: https://github.com/marcizhu/microk8s-nas.git
      targetRevision: master
      path: apps/transmission
  destination:
    server: https://kubernetes.default.svc
    namespace: transmission
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
