apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: open-webui-secret
  namespace: open-webui
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgAEIQR0sRleiF8sGU2+hE3wKBY007MOo6mBd8HEPQHuD5+/aoDuQMZ/9scnxcd0ougWMt7pzg2BTkGHvc2UvGUIqmYKWotl7IIEqbysEzVi2OTf/JsQEEjc+6IM2utQipBs9LC4NKvgS5pw62VoC6a0cX8EnLGDzH1SrdhBLtvs/U6j7SE9X2fn5jm+bsIUcS4iANDDYrDFwVi7W5JhG9yBiBXzHoDbGVqS3qVY+vCdZtqNMGlzLl1B4r8p8Rr/k8jL840wj3xZrYKYFDEPAO0OkGctPNombjJXRNgR760zbHhlvywhmVYD/FbQtpwtYxL9N3RCcPMyTeJ4nhAKWi9CNni25hIFiTph1533hPI/tzrlcZZcQQnI1Y/zucLYgwgTcZtjYR6pBbOokAAnS0qsj1BCfMlsy9xBeKINKV+RTU4suaBm5rdT4ebaKZ8JOhNSqCyY7G5r6LbXXfzzlhVOCkO4MA0FKYoYmJnHNJOYII8hJl13TFIuIwS+crYjfed//8Bzk2riOoPee7Bai4Pb6CmjGvI7gyPRC3gu7BkS/0tuQJvmQJobhO0yMge9fQU97TuODyUNdJYHy8Tt0Sl2NMkQY2v1eq3oLjSTqzPwMa8UCZoqkQOzq/zZkROBrkY5BEYLk4gMPSZ9sQ8XOTpdgtXLcGfe71lsGpWnsbkKXhu32MikWRTRlQLE27/C5KuXJIQcr1tJ5QE0Uxu9KLqbkJHkgLhSz5c482Hl4I27WHOleODKJEME5ZqRYXzG89DxM4GTp1knPJMO03XlTES4
  template:
    metadata:
      creationTimestamp: null
      name: open-webui-secret
      namespace: open-webui
